### ISSUE TITLE
Maintainers 😺

### ISSUE THREAD

**Issue by a-probably-normal-cat** [a-normal-cat/add-some-numbers#2]
# What? 
Are you looking for new maintainers. I would be more than happy to help out on that front. 😸

# Why? 
I have seen a number of outstanding Pull Requests on this library. Keeping addition cosmic ray safe is critical for some of the work I am doing. Would you like any help with reviewing them / getting them merged?

**Comment by a-normal-cat** [comment]
Help is always appreciated! Have sent you an invite to the project 🙌
